name: GitHub Classroom Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Run Autograder
        timeout-minutes: 15
        uses: education/autograding@v1
